POST http://localhost:3333/trips
Content-Type: application/json

{
  "destination": "Lugar de Teste",
  "starts_at": "2024-07-10 18:32:00",
  "ends_at": "2024-08-10 19:32:00",
  "owner_name": "Greg",
  "owner_email": "antonioimportant@gmail.com",
  "emails_to_invite": [
    "teste@gmail.com",
    "teste2@gmail.com",
    "teste3@gmail.com"
  ]
}